name: release

on:
  push:
  pull_request:
  release:
    types: [published]

env:
  SKF_SET_NAME: "${{ github.event.repository.name }}"

jobs:

  skf-archive:
    runs-on: ubuntu-latest

  steps:

  - name: Checkout sk-set
    uses: actions/checkout@4
    with:
      fetch-depth: 0

  - name: Get version number
    run: |
      GIT_TAG=$(git describe --tags --match 'v[0-9]*-[0-9]*')
      echo "SKF_SET_VERSION=${GIT_TAG#v}" >> ${GITHUB_ENV}
      echo "ARCHIVE_NAME=${SKF_SET_NAME}-${SKF_SET_VERSION}" >> ${GITHUB_ENV}

  - name: Create archive
    run: |
      mkdir -p _build/${ARCHIVE_NAME}
      cp $(find . -maxdepth 1 -not -type 'd') _build/${ARCHIVE_NAME}
      cp skf/*.skf _build/${ARCHIVE_NAME}
      tar -C _build -v -J -f ${ARCHIVE_NAME}.tar.xz ${ARCHIVE_NAME}

  - name: Upload archive
    run: |
      uses: actions/upload-artifact@4
      with:
        name: ${{ ARCHIVE_NAME }}.tar.xz
        path: ${{ ARCHIVE_NAME }}.tar.xz
